// Byte-exact port of CPython's `html.unescape` (Lib/html/__init__.py, frozen interpreter 3.14.x).
//
// SECURITY-CRITICAL: this feeds `stripPrivilegedTags` in the trust-tier input-wrapping subsystem.
// Any divergence from CPython is a parity finding. The algorithm is reproduced step-for-step:
//
//   def unescape(s):
//       if '&' not in s: return s
//       return _charref.sub(_replace_charref, s)
//
//   _charref = re.compile(r'&(#[0-9]+;?|#[xX][0-9a-fA-F]+;?|[^\t\n\f <&#;]{1,32};?)')
//
//   def _replace_charref(s):
//       s = s.group(1)
//       if s[0] == '#':
//           if s[1] in 'xX': num = int(s[2:].rstrip(';'), 16)
//           else:            num = int(s[1:].rstrip(';'))
//           if num in _invalid_charrefs:                       return _invalid_charrefs[num]
//           if 0xD800 <= num <= 0xDFFF or num > 0x10FFFF:      return '�'
//           if num in _invalid_codepoints:                     return ''
//           return chr(num)
//       else:
//           if s in _html5: return _html5[s]
//           for x in range(len(s)-1, 1, -1):
//               if s[:x] in _html5: return _html5[s[:x]] + s[x:]
//           else:                   return '&' + s
//
// Codepoint-fidelity note: CPython operates on Unicode code points. JS strings are UTF-16, but the
// `_charref` regex matches only ASCII bytes (`#`, hex/decimal digits, and the `[^\t\n\f <&#;]`
// class which can include astral chars). `String.prototype.slice` on the matched group operates on
// UTF-16 code units; because the named-charref group is bounded to {1,32} and matched purely by the
// regex (no manual indexing into astral chars within the algorithm beyond `s[0]`/`s[1]` which are
// always ASCII `#`/`x`/`X`/digits in the numeric branch), the with-/without-semicolon and
// progressively-shorter-prefix logic reproduces CPython exactly for all entity inputs.

import { HTML5_ENTITIES } from "./html_entities_data.js";

// CPython html._invalid_charrefs: numeric refs that map to a fixed replacement (C1 cp1252 remap +
// NUL→U+FFFD + 0x0D→CR). Generated byte-exact from the frozen interpreter.
const INVALID_CHARREFS: ReadonlyMap<number, string> = new Map<number, string>([
  [0x00, "�"], // REPLACEMENT CHARACTER
  [0x0d, "\r"], // CARRIAGE RETURN
  [0x80, "€"], // EURO SIGN
  [0x81, ""], // <control>
  [0x82, "‚"], // SINGLE LOW-9 QUOTATION MARK
  [0x83, "ƒ"], // LATIN SMALL LETTER F WITH HOOK
  [0x84, "„"], // DOUBLE LOW-9 QUOTATION MARK
  [0x85, "…"], // HORIZONTAL ELLIPSIS
  [0x86, "†"], // DAGGER
  [0x87, "‡"], // DOUBLE DAGGER
  [0x88, "ˆ"], // MODIFIER LETTER CIRCUMFLEX ACCENT
  [0x89, "‰"], // PER MILLE SIGN
  [0x8a, "Š"], // LATIN CAPITAL LETTER S WITH CARON
  [0x8b, "‹"], // SINGLE LEFT-POINTING ANGLE QUOTATION MARK
  [0x8c, "Œ"], // LATIN CAPITAL LIGATURE OE
  [0x8d, ""], // <control>
  [0x8e, "Ž"], // LATIN CAPITAL LETTER Z WITH CARON
  [0x8f, ""], // <control>
  [0x90, ""], // <control>
  [0x91, "‘"], // LEFT SINGLE QUOTATION MARK
  [0x92, "’"], // RIGHT SINGLE QUOTATION MARK
  [0x93, "“"], // LEFT DOUBLE QUOTATION MARK
  [0x94, "”"], // RIGHT DOUBLE QUOTATION MARK
  [0x95, "•"], // BULLET
  [0x96, "–"], // EN DASH
  [0x97, "—"], // EM DASH
  [0x98, "˜"], // SMALL TILDE
  [0x99, "™"], // TRADE MARK SIGN
  [0x9a, "š"], // LATIN SMALL LETTER S WITH CARON
  [0x9b, "›"], // SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
  [0x9c, "œ"], // LATIN SMALL LIGATURE OE
  [0x9d, ""], // <control>
  [0x9e, "ž"], // LATIN SMALL LETTER Z WITH CARON
  [0x9f, "Ÿ"], // LATIN CAPITAL LETTER Y WITH DIAERESIS
]);

// CPython html._invalid_codepoints: numeric refs that map to the empty string (control chars +
// non-characters). Generated byte-exact from the frozen interpreter.
const INVALID_CODEPOINTS: ReadonlySet<number> = new Set<number>([
  // 0x0001 to 0x0008
  0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8,
  // 0x000E to 0x001F
  0xe, 0xf, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
  // 0x007F to 0x009F
  0x7f, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91,
  0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0x9b, 0x9c, 0x9d, 0x9e, 0x9f,
  // 0xFDD0 to 0xFDEF
  0xfdd0, 0xfdd1, 0xfdd2, 0xfdd3, 0xfdd4, 0xfdd5, 0xfdd6, 0xfdd7, 0xfdd8, 0xfdd9, 0xfdda, 0xfddb, 0xfddc, 0xfddd,
  0xfdde, 0xfddf, 0xfde0, 0xfde1, 0xfde2, 0xfde3, 0xfde4, 0xfde5, 0xfde6, 0xfde7, 0xfde8, 0xfde9, 0xfdea, 0xfdeb,
  0xfdec, 0xfded, 0xfdee, 0xfdef,
  // others
  0xb, 0xfffe, 0xffff, 0x1fffe, 0x1ffff, 0x2fffe, 0x2ffff, 0x3fffe, 0x3ffff, 0x4fffe, 0x4ffff, 0x5fffe, 0x5ffff,
  0x6fffe, 0x6ffff, 0x7fffe, 0x7ffff, 0x8fffe, 0x8ffff, 0x9fffe, 0x9ffff, 0xafffe, 0xaffff, 0xbfffe, 0xbffff,
  0xcfffe, 0xcffff, 0xdfffe, 0xdffff, 0xefffe, 0xeffff, 0xffffe, 0xfffff, 0x10fffe, 0x10ffff,
]);

// CPython `_charref` regex verbatim. Global flag so `String.prototype.replace` walks every match
// (CPython `re.sub` replaces all). The `[^\t\n\f <&#;]` class and the {1,32} bound match CPython
// byte-for-byte (no IGNORECASE; `#[xX]` is the only case-insensitive piece, encoded explicitly).
// Bounded {1,32} quantifier, single alternation level, no nested/ambiguous repetition: linear-time,
// no catastrophic backtracking (detect-unsafe-regex does not fire — no disable directive needed).
const CHARREF = /&(#[0-9]+;?|#[xX][0-9a-fA-F]+;?|[^\t\n\f <&#;]{1,32};?)/g;

// Strip a single trailing ';' if present (CPython `str.rstrip(';')` removes ALL trailing ';', but
// the `_charref` regex captures at most ONE trailing ';' in the numeric branches, so removing one
// is equivalent here; we mirror rstrip semantics anyway for exactness).
function rstripSemicolons(s: string): string {
  let end = s.length;
  while (end > 0 && s.charCodeAt(end - 1) === 0x3b /* ';' */) {
    end -= 1;
  }
  return s.slice(0, end);
}

// CPython `chr(num)`: the Unicode code point as a string. JS `String.fromCodePoint` produces the
// correct UTF-16 encoding (surrogate pair for astral). Surrogates / out-of-range are filtered
// upstream before this is reached, matching CPython's guard ordering.
function chrCodePoint(num: number): string {
  return String.fromCodePoint(num);
}

// Mirror of CPython `_replace_charref` over the captured group-1 string (no leading '&').
function replaceCharref(group1: string): string {
  if (group1.charCodeAt(0) === 0x23 /* '#' */) {
    // numeric charref
    const second = group1.charCodeAt(1);
    let num: number;
    if (second === 0x78 /* 'x' */ || second === 0x58 /* 'X' */) {
      num = Number.parseInt(rstripSemicolons(group1.slice(2)), 16);
    } else {
      num = Number.parseInt(rstripSemicolons(group1.slice(1)), 10);
    }
    const invalid = INVALID_CHARREFS.get(num);
    if (invalid !== undefined) {
      return invalid;
    }
    if ((num >= 0xd800 && num <= 0xdfff) || num > 0x10ffff) {
      return "�";
    }
    if (INVALID_CODEPOINTS.has(num)) {
      return "";
    }
    return chrCodePoint(num);
  }
  // named charref
  const exact = HTML5_ENTITIES.get(group1);
  if (exact !== undefined) {
    return exact;
  }
  // find the longest matching name (as defined by the standard):
  // for x in range(len(s)-1, 1, -1): if s[:x] in html5: return html5[s[:x]] + s[x:]
  for (let x = group1.length - 1; x > 1; x -= 1) {
    const prefix = group1.slice(0, x);
    const matched = HTML5_ENTITIES.get(prefix);
    if (matched !== undefined) {
      return matched + group1.slice(x);
    }
  }
  // else branch: no prefix matched
  return "&" + group1;
}

/**
 * Byte-exact port of CPython `html.unescape`. Converts all named and numeric character references
 * in `s` to the corresponding Unicode characters, using the HTML5 rules for valid AND invalid
 * references. Used by the trust-tier wrapper to canonicalize entity-encoded privileged tags before
 * stripping (so `&lt;diff&gt;` is decoded then stripped alongside the literal form).
 */
export function htmlUnescape(s: string): string {
  if (!s.includes("&")) {
    return s;
  }
  return s.replace(CHARREF, (_full, group1: string) => replaceCharref(group1));
}
